# Python Basics 

# 'numpy 
- one of the core packages for a numerical computing in python 
- many packages are built on top of numpy 
- numpy has been optimized for processing: efficient use of memory, faster memory acces

In [1]:
# import numpy with standard abbreviation 
import numpy as np 

# Variables
we can think about variables as a name we assign to particularobejcts in python, for example 

In [11]:
# assign a small array to a variable a 
# np array
a = np.array( [[1,1,2], [3,5,8] ] )

# When we run the cell, we store the variable and its value. We can the variables value in two ways 

a

In [8]:
print(a)

[[1 1 2]
 [3 5 8]]


# naming variables 
in the class we are going to use 'snake_case' for naming variables (all small caps with udnerscore to separrate words) 

# Variables and objects 

**object** : often encountered in python documentation and tutorials 
object is a bunudle of properties and actions about something specific 

Example: 

- object: data frame (contains properties and actions)
- properties: number of rows, names of columns, data created 
- actions: selecitng a row, adding a new column, etc. 

A variable is a name we give a specific object, and the same object can be referenced to by different variables 

Example: 
- the sun (actual sar at the center of the solar system) = object 
- sol = Spanish work for sun = variable, naming object sun 
- soleil = French for Sun = another variable

In practice: we will use object and variable interchangeably 

# Types 

Each object in python has a type

type = what kind of object the thing is 

We can also call the type of the object, the **class** of the object

We can see the type/class of an object using the type function 

In [12]:
print(a)
type(a)
#always check what type of object you have to get more info! step zero!

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The numpy.ndarray is the core object/data type in the numpy packages
We can check the type of an entry in the array by indexing 

In [13]:
#print first in corner so index, index happens in square brackets, indexing starts at 0 in python 
#access first row first column 

print(a[0,0])

1


In [14]:
#1 is stored as integer on 64 bits of memory , how much space number takes in computer 

type(a[0,0])


numpy.int64

In [16]:
# how to access value 5 in array a? 

print(a[1,1])

5


## Functions

print was our example of a python function! :) 

A fucntion: 
- take in a set of **arguments** separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might see argument mroe foten in documentation 

We can ask informaiton about a function by executing ? followed by function name 

In [18]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: fucntion showing all of its arguments in parenthesis 
- then a short description of what the function does 
- finally, a list of the arguments and a brief explanation of each of them 

(file, sep, end, flsuh = arguments and explanation for each) 

Different types of argumentn sinside the paranethesis. Roughyl speaking there are two types of arguments 

- **non-optional arguments**: arguments you need to specify for the fucntion to do something 
- **optional arguments**: arguments that are pre-filled with a default value bythe function, we can 
override them, optional arguments appear inside the parenthesis () in the form 

`optional argument = default_value' 

optional arguments: file, sep, end flush (insdie argument theres a deffault value whiel value is non optional) 

In [19]:
print('changing the default argument of the print function', end=':)')

#end is optional arguemnt 

changing the default argument of the print function:)

In [20]:
print('changing the default argument of the print function')


changing the default argument of the print function
